Array.prototype.random = function() {
	return this[Math.floor(Math.random() * this.length)];		
}

var word = [
	"Waihopai",
	"INFOSEC",
	"InformationSecurity",
	"InformationWarfare",
	"IW",
	"IS",
	"Priavacy",
	"InformationTerrorism",
	"TerrorismDefensiveInformation",
	"DefenseInformationWarfare",
	"offensiveInformation",
	"NationalInformationInfrastructure",
	"InfoSec",
	"Reno",
	"Compsec",
	"computerTerrorism",
	"firewalls",
	"secureInternetConnections",
	"ISS",
	"passwords",
	"DefConV",
	"hackers",
	"encryption",
	"espionage",
	"USDOJ",
	"NSA",
	"CIA",
	"SSL",
	"FBI",
	"SecretService",
	"USSS",
	"Defcon",
	"military",
	"White House",
	"undercover",
	"NCCS",
	"Mayfly",
	"PGP",
	"PEM",
	"RSA",
	"PerlRSA",
	"MSNBC",
	"bet",
	"AOL",
	"AOLTOS",
	"CIS",
	"CBOT",
	"AIMSX",
	"STARLAN",
	"3B2",
	"BITNET",
	"COSMOS",
	"DATTA",
	"E911",
	"FCIC",
	"HTCIA",
	"IACIS",
	"JANET",
	"JICC",
	"ReMOB",
	"LEETAC",
	"UTU",
	"VNET",
	"BRLO",
	"BZ",
	"CANSLO",
	"CBNRC",
	"CIDA",
	"JAVA",
	"ActiveX",
	"Compsec97",
	"LLC",
	"DERA",
	"Mavricks",
	"meta-hackers",
	"SteveCase",
	"Tools",
	"Telex",
	"MilitaryIntelligence",
	"Scully",
	"Flame",
	"Infowar",
	"Bubba",
	"Freeh",
	"Archives",
	"Sundevel",
	"jack",
	"investigation",
	"ISACA",
	"NCSA",
	"spook words",
	"Verisign",
	"Secure",
	"ASIO",
	"Lebed",
	"ICE",
	"NRO",
	"Lexis-Nexis",
	"NSCT",
	"SCIF",
	"FLiR",
	"Lacrosse",
	"Flashbangs",
	"HRT",
	"DIA",
	"USCOI",
	"CID",
	"BOP",
	"FINCEN",
	"FLETC",
	"NIJ",
	"ACC",
	"AFSPC",
	"ARPA",
	"LABLINK",
	"USACIL",
	"USCG",
	"NRC",
	"CDC",
	"DOE",
	"FMS",
	"HPCC",
	"NTIS",
	"SEL",
	"USCODE",
	"CISE",
	"SIRC",
	"CIM",
	"ISN",
	"DJC",
	"SGC",
	"UNCPCJ",
	"CFC",
	"DREO",
	"CDA",
	"DRA",
	"SHAPE",
	"SACLANT",
	"BECCA",
	"DCJFTF",
	"HALO",
	"HAHO",
	"FKS",
	"868",
	"GCHQ",
	"DITSA",
	"SORT",
	"AMEMB",
	"NSG",
	"HIC",
	"EDI",
	"SAS",
	"SBS",
	"UDT",
	"GOE",
	"GEO",
	"Masuda",
	"Forte",
	"AT",
	"GIGN",
	"ExonShell",
	"CQG",
	"CONUS",
	"CTU",
	"RCMP",
	"GRU",
	"SASR",
	"GSG-9",
	"22ndSAS",
	"GEOS",
	"EADA",
	"BBE",
	"STEP",
	"Echelon",
	"Dictionary",
	"MD2",
	"MD4",
	"MDA",
	"MYK",
	"747777767",
	"MI5",
	"737",
	"MI6",
	"757",
	"Kh-11",
	"Shayet-13",
	"SADMS",
	"Spetznaz",
	"Recce",
	"707",
	"CIO",
	"NOCS",
	"Halcon",
	"Duress",
	"RAID",
	"Psyops",
	"grom",
	"D11",
	"SERT",
	"VIP",
	"ARC",
	"SETTeam",
	"MP5k",
	"DREC",
	"DEVGRP",
	"DF",
	"DSD",
	"FDM",
	"GRU",
	"LRTS",
	"SIGDEV",
	"NACSI",
	"PSAC",
	"PTT",
	"RFI",
	"SIGDASYS",
	"TDM",
	"SUKLO",
	"SUSLO",
	"TELINT",
	"TEXTA",
	"ELF",
	"LF",
	"MF",
	"VHF",
	"UHF",
	"SHF",
	"SASP",
	"WANK",
	"Colonel",
	"domesticDisruption",
	"smuggle",
	"15kg",
	"nitrate",
	"Pretoria",
	"M14",
	"enigma",
	"BletchleyPark",
	"Clandestine",
	"nkvd",
	"argus",
	"afsatcom",
	"CQB",
	"NVD",
	"CounterTerrorismSecurity",
	"RapidReaction",
	"CorporateSecurity",
	"Police",
	"sniper",
	"PPS",
	"ASIS",
	"ASLET",
	"TSCM",
	"SecurityConsulting",
	"HighSecurity",
	"SecurityEvaluation",
	"ElectronicSurveillance",
	"MI17",
	"Counterterrorism",
	"spies",
	"eavesdropping",
	"debugging",
	"interception",
	"COCOT",
	"rhosts",
	"rhost",
	"SETA",
	"Amherst",
	"Broadside",
	"Capricorn",
	"Gamma",
	"Gorizont",
	"Guppy",
	"Inosphere",
	"Mole",
	"Keyhole",
	"Kilderkin",
	"Artichoke",
	"Badger",
	"Cornflower",
	"Daisy",
	"Egret",
	"Iris",
	"Hollyhock",
	"Jasmine",
	"Juile",
	"MacintoshFirewalls",
	"MacintoshInternetSecurity",
	"topSecret",
	"MPRI",
	"stakeout",
	"FLAME",
	"Speakeasy",
	"GSA",
	"RandCorporation",
	"RetinalFetish",
	"InternetUnderground",
	"Fetish",
	"Wackendude",
	"Nerd",
	"Middleman",
	"KLM",
	"Blackbird",
	"plutonium",
	"PPP",
	"Blackmednet",
	"Propaganda",
	"ABC",
	"SatellitePhones",
	"nuclear",
	"FBI",
	"Panama",
	"fissionable",
	"SearsTower",
	"NORAD",
	"DeltaForce",
	"SEAL",
	"virtual",
	"Dolch",
	"BlackOps",
	"utopia",
	"orthodox",
	"MD5",
	"IDEA",
	"illuminati",
	"president",
	"assassinate",
	"virus",
	"cybercash",
	"Whitewater",
	"veggie",
	"railGun",
	"chosen",
	"PRIME",
	"fraud",
	"gorilla",
	"unclassified",
	"rebels",
	"Leitrim",
	"cryptanalysis",
	"TEMPSET",
	"jihad",
	"Uzi",
	"SWAT",
	"industrialEspionage",
	"dataHavens",
	"Anonymous"
]

var templates = [

	"A bad {{word}} always turns up. #{{word}} #{{word}}",
	"A barking {{word}} never bites. #{{word}} #{{word}}",
	"A {{word}} is a man's best. {{word}} #{{word}} #{{word}}",
	"A {{word}} and his {{word}} are soon parted. #{{word}}",
	"A jack of all {{word}} is a master of {{word}}. #{{word}}",
	"A {{word}} in need is a {{word}} indeed. #{{word}}",
	"A foolish {{word}} is the hobgoblin of little {{word}}. #{{word}}",
	"A man's {{word}} is his {{word}}. #{{word}}",
	"A {{word}} is as good as a wink to a blind {{word}}. #{{word}}",
	"A {{word}} saved is a {{word}} earned. #{{word}}",
	"A rolling {{word}} gathers no {{word}}. #{{word}}",
	"{{word}} speaks louder than words. #{{word}}",
	"Absence makes the {{word}} grow fonder. #{{word}}",
	"All for {{word}} and {{word}} for all. #{{word}}",
	"{{word}} can be deceiving. #{{word}}",
	"Ask and {{word}} shall receive. #{{word}}",
	"Ask no {{word}} and hear no {{word}}. #{{word}}",
	"{{word}} is only skin deep. #{{word}}",
	"Better {{word}} than sorry. #{{word}}",
	"Beware of {{word}}s bearing gifts. #{{word}}",
	"{{word}} is the soul of {{word}}. #{{word}}",
	"{{word}} always rises to the top. #{{word}}",
	"Don't foul your own {{word}}. #{{word}}",
	"Don't put all your {{word}} into one basket. #{{word}}",
	"Don't bite off the {{word}} that feeds you. #{{word}}",
	"Don't burn the {{word}} at both ends. #{{word}} #{{word}}",
	"{{word}} is the better part of {{word}}. #{{word}}",
	"Don't put the {{word}} before the {{word}}. #{{word}}",
	"{{word}} is one percent inspiration and 99 percent {{word}}. #{{word}}",
	"{{word}} think alike. #{{word}} #{{word}}",
	"{{word}} is as {{word}} does. #{{word}}",
	"{{word}} hath no fury like a {{word}} scorned. #{{word}}",
	"{{word}} is where the heart is. #{{word}} #{{word}}.",
	"{{word}} springs eternal in the {{word}}. #{{word}}",
	"If the {{word}} fits, wear it. #{{word}}",
	"{{word}} is the sincerest form of {{word}}. #{{word}}",
	"In for a {{word}}, in for a {{word}}. #{{word}}",
	"In the country of the {{word}}, the {{word}} is king. #{{word}}",
	"In the spring a {{word}}'s fancy lightly turns to thoughts of {{word}}. #{{word}}",
	"It takes {{word}} to tango. #{{word}} #{{word}}",
	"It's not over until the {{word}} sings. #{{word}}",
	"Keep your {{word}} dry. #{{word}} #{{word}}",
	"Keep your {{word}} to the grindstone. #{{word}}",
	"Know which side your {{word}} is buttered on. #{{word}} #{{word}}",
	"{{word}} is the best medicine. #{{word}} #{{word}}",
	"Leave no {{word}} unturned. #{{word}} #{{word}}",
	"Let {{word}} take its course. #{{word}}",	
	"{{word}} conquers all. #{{word}}",
	"Make {{word}} slowly. #{{word}}",
	"{{word}} makes right. #{{word}} #{{word}}",
	"{{word}} loves company. #{{word}} #{{word}}",
	"{{word}} hath charms to soothe the savage {{word}}. #{{word}}",
	"{{word}} abhors a vacuum. #{{word}} #{{word}}",
	"Nothing is certain but {{word}} and {{word}}. #{{word}}",
	"Old {{word}} dies hard. #{{word}} #{{word}}",
	"{{word}} never knocks twice. #{{word}}",
	"{{word}} is nine-tenths of the law. #{{word}}",
	"{{word}} makes strange bedfellows. #{{word}} #{{word}} #{{word}}",
	"{{word}} makes perfect. #{{word}}",
	"One rotten {{word}} spoils the {{word}}. #{{word}}",
	"One good {{word}} deserves another. #{{word}}",
	"One man's {{word}} is another man's {{word}}. #{{word}}",
	"One {{word}} is worth a thousand words. #{{word}}",
	"{{word}} goeth before the fall. #{{word}} #{{word}}",
	"{{word}} is the thief of time. #{{word}} #{{word}}",
	"{{word}} is a dish best eaten cold. #{{word}} #{{word}}",
	"{{word}} wasn't built in a day. #{{word}} #{{word}}",
	"Take the {{word}} with the sweet. #{{word}} #{{word}}",
	"The {{word}} doesn't fall far from the tree. #{{word}}",
	"The {{word}} can cite Scripture for his purpose. #{{word}} #{{word}}",
	"The {{word}} cannot change its spots. #{{word}}",
	"The {{word}} must go on. #{{word}} #{{word}}",
	"There are plenty of {{word}} in the sea. #{{word}} #{{word}}"

]

var template = templates.random();
var final_output = template;

function render(final_output,id) {
	console.log(template);
	var parts = final_output.split("{{" + id + "}}"); 
	var output = "";
	
		if(parts.length > 0) {
			parts.forEach(function(part) {
				output += part;
				output += word.random();
				final_output = output;
		});
	}
	return final_output;

}

final_output = render(final_output, "word");
document.write('<span class= "statusGenerated" >' + final_output + '</span>');


var generateStatus = document.getElementById("twitter-generate");
generateStatus.addEventListener("click", render, false);



// function postToTwitter(STAT, LAT, LON){
// 	var url = 'https://api.twitter.com/1.1/statuses/update.json&status='+STAT+'&lat='+LAT+'&long='+LON;

// 		$.getJSON(url, function(data){
	       
// 	    })
	    
// 	    .success(function(response) { 
// 	        console.log("Information successfully posted to Twitter");
	     
// 	    })
// 	    .error(function(response) { 
// 	        console.log("Sorry. There was an error.");
// 			console.log(response);
	        
// 	    })
// 	.complete(function() {  

// }  